apiVersion: v1
kind: Service
metadata:
  name: go-cpu-intensive
  namespace: demo
  labels:
    app: go-cpu-intensive
spec:
  type: ClusterIP
  selector:
    app: go-cpu-intensive
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-cpu-intensive
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-cpu-intensive
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Object
    object:
      describedObject:
        apiVersion: v1
        kind: Service
        name: go-cpu-intensive
      metric:
        name: requests_per_second
      target:
        type: AverageValue # divide metric value by the number of pods
        averageValue: "10" # or k8s-style "10000m"
  - type: Object
    object:
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: go-cpu-intensive
      metric:
        name: request_duration_seconds_90tile
      target:
        type: Value
        value: 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-cpu-intensive
  namespace: demo
  labels:
    app: go-cpu-intensive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-cpu-intensive
  template:
    metadata:
      labels:
        app: go-cpu-intensive
    spec:
      containers:
      - name: go-cpu-intensive
        image: ryojpn/go-cpu-intensive:arm64
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 250Mi
        ports:
        - containerPort: 8080
