repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-adapter
  namespace: monitoring
  chart: prometheus-community/prometheus-adapter
  values:
  - ./values.yml